spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 1
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: false
        properties:
            hibernate:
                format_sql: true
        open-in-view: false
    data:
        redis:
            host: localhost
            port: 6379

security:
    jwt:
        secret-key: o9354rn9mm94kmd93d903kj209kksdfkmlsdfkmsdf9341924124
        expiration-time: 3600000

logging:
    level:
      org.springframework.security: trace

server:
    port: 8082
